keys:
  - &larsg age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy

creation_rules:
  # Project management secrets
  - path_regex: project/secrets.yaml
    key_groups:
      - age:
          - *larsg
  # Infrastructure deployment secrets
  # Development
  - path_regex: infrastructure/environments/development/secrets.yaml
    key_groups:
      - age:
          - *larsg
