#cloud-config

package_update: true
package_upgrade: true

packages:
  - git
  - ufw

write_files:
  # Reconciliation service & timer
  - path: /etc/systemd/system/reconcile.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Run reconciliation script
      Requires=setup-docker-compose.service
      After=setup-docker-compose.service
      After=docker.service

      [Service]
      Type=oneshot
      ExecStartPre=/bin/mkdir -p /srv/gitops
      ExecStart=/usr/local/bin/reconcile.sh

      [Install]
      WantedBy=multi-user.target

  - path: /etc/systemd/system/reconcile.timer
    permissions: '0644'
    content: |
      [Unit]
      Description=Timer for reconciliation script

      [Timer]
      OnBootSec=${boot_delay}
      OnUnitActiveSec=${reconciliation_intervall}
      Persistent=true

      [Install]
      WantedBy=timers.target

  - path: /usr/local/bin/reconcile.sh
    permissions: '0755'
    content: |
      ${indented_reconciliation_script}

  # Limit journald log retention
  - path: /etc/systemd/journald.conf.d/99-limits.conf
    permissions: '0644'
    content: |
      [Journal]
      SystemMaxUse=200M
      RuntimeMaxUse=50M

  # Harden Kernel and Network
  - path: /etc/sysctl.d/99-hardening.conf
    permissions: '0644'
    content: |
      # Kernel hardening
      kernel.kptr_restrict=2
      kernel.dmesg_restrict=1
      fs.protected_symlinks=1
      fs.protected_hardlinks=1
      kernel.perf_event_paranoid=2
      kernel.pid_max=65536

      # Network - IPv4
      net.ipv4.conf.all.rp_filter=2
      net.ipv4.conf.default.rp_filter=2
      net.ipv4.conf.all.accept_redirects=0
      net.ipv4.conf.default.accept_redirects=0
      net.ipv4.conf.all.send_redirects=0
      net.ipv4.conf.default.send_redirects=0
      net.ipv4.icmp_echo_ignore_broadcasts=1
      net.ipv4.icmp_ignore_bogus_error_responses=1
      net.ipv4.conf.all.accept_source_route=0
      net.ipv4.conf.default.accept_source_route=0
      net.ipv4.tcp_syncookies=1
      net.ipv4.tcp_fin_timeout=15

      # Network - IPv6
      net.ipv6.conf.all.accept_redirects=0
      net.ipv6.conf.default.accept_redirects=0
      net.ipv6.conf.all.accept_source_route=0
      net.ipv6.conf.default.accept_source_route=0

  # Harden baseline image
  - path: /etc/systemd/system/harden.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Disable unneeded baseline services
      After=network.target

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/local/bin/harden.sh

      [Install]
      WantedBy=multi-user.target

  - path: /usr/local/bin/harden.sh
    permissions: '0755'
    content: |
      #!/bin/sh
      set -e

      # Disable package mgmt noise
      systemctl disable --now apt-daily.timer apt-daily-upgrade.timer unattended-upgrades.service || true
      systemctl mask unattended-upgrades.service || true
      systemctl disable --now dpkg-db-backup.service man-db.timer || true

      # Disable legacy daemons not used
      systemctl disable --now acpid.service acpid.socket acpid.path || true
      systemctl disable --now atd.service || true
      systemctl disable --now cron.service logrotate.service rc-local.service || true

      # Storage-related stuff not relevant for ephemeral hosts
      systemctl disable --now lvm2-monitor.service lvm2-lvmpolld.socket dm-event.socket mdadm-shutdown.service || true
      systemctl disable --now e2scrub_all.service e2scrub_reap.service fstrim.service || true
      systemctl disable --now iscsi.service iscsid.service iscsi-shutdown.service fcoe.service rbdmap.service || true

      # Desktop/interactive junk
      systemctl disable --now display-manager.service console-screen.service plymouth-quit-wait.service plymouth-start.service || true

      # Get rid of unused ttys (leave tty1 for console recovery)
      for n in 2 3 4 5 6; do
        systemctl disable --now getty@tty$n.service || true
      done
      # drop extra serial consoles
      systemctl disable --now serial-getty@ttyAMA0.service serial-getty@ttyS1.service serial-getty@ttyS2.service serial-getty@ttyS3.service || true

      # Kill systemd "nice to haves"
      systemctl disable --now systemd-repart.service systemd-pstore.service || true

      # Kill legacy log service (we use journald)
      systemctl disable --now rsyslog.service || true
      systemctl mask rsyslog.service || true

      # Restart journald so it picks up a clean state
      systemctl restart systemd-journald

  # Firewall service
  - path: /etc/systemd/system/setup-firewall.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Setup strict firewall rules
      After=network.target
      Before=ufw.service
      Before=reconcile.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/local/bin/setup-firewall.sh

      [Install]
      WantedBy=multi-user.target

  - path: /usr/local/bin/setup-firewall.sh
    permissions: '0755'
    content: |
      #!/bin/sh
      set -e
      ufw allow 22/tcp  # TODO! remove once SSH is gone
      ufw allow 80/tcp
      ufw allow 443/tcp
      ufw default deny incoming
      ufw default allow outgoing
      ufw --force enable

  # Docker install
  - path: /etc/systemd/system/setup-docker-compose.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Setup Docker Compose with dependencies
      Before=reconcile.service
      Wants=network-online.target
      After=network-online.target

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/local/bin/setup-docker-compose.sh

      [Install]
      WantedBy=multi-user.target

  - path: /usr/local/bin/setup-docker-compose.sh
    permissions: '0755'
    content: |
      #!/bin/sh
      set -e
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      chmod a+r /etc/apt/keyrings/docker.gpg
      echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
        https://download.docker.com/linux/debian \
        $(lsb_release -cs) stable" \
        > /etc/apt/sources.list.d/docker.list
      apt-get update
      apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
      systemctl enable --now docker

  # Docker prune
  - path: /etc/systemd/system/docker-prune.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Nightly Docker prune
      After=docker.service
      Requires=docker.service

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/docker system prune --force

      [Install]
      WantedBy=multi-user.target

  - path: /etc/systemd/system/docker-prune.timer
    permissions: '0644'
    content: |
      [Unit]
      Description=Run nightly docker prune

      [Timer]
      OnCalendar=daily
      RandomizedDelaySec=1h
      Persistent=true

      [Install]
      WantedBy=timers.target

  # TODO! Disable SSH once we have verified the module works
  # SSH removal script
  # - path: /etc/systemd/system/disable-ssh.service
  #   permissions: '0644'
  #   content: |
  #     [Unit]
  #     Description=Disable SSH access
  #     After=network.target

  #     [Service]
  #     Type=oneshot
  #     RemainAfterExit=yes
  #     ExecStart=/usr/local/bin/disable-ssh.sh

  # - path: /usr/local/bin/disable-ssh.sh
  #   permissions: '0755'
  #   content: |
  #     #!/bin/sh
  #     set -e
  #     systemctl disable --now ssh.service

  # Temporary hardening
  - path: /etc/ssh/sshd_config.d/99-temporary-dev.conf
    permissions: '0644'
    content: |
      PermitRootLogin prohibit-password
      PasswordAuthentication no
      ChallengeResponseAuthentication no
      PubkeyAuthentication yes
      AllowAgentForwarding no
      AllowTcpForwarding no
      X11Forwarding no

runcmd:
  - sysctl --system
  - systemctl daemon-reload
  - systemctl enable --now harden.service
  - systemctl enable --now setup-firewall.service
  - systemctl enable --now setup-docker-compose.service
  - systemctl enable --now reconcile.timer
  - systemctl enable --now docker-prune.timer
