name: student-deployment-1

services:
  ingress:
    image: "traefik:v3.4"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entryPoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=false"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.http.routers.traefik.rule=PathPrefix(`/traefik`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.middlewares.strip-traefik-prefix.stripprefix.prefixes=/traefik"
      - "traefik.http.routers.traefik.middlewares=strip-traefik-prefix"
